[project]
name = "rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.8.3",
    "chromadb>=1.1.0",
    "duckdb>=1.4.3",
    "duckdb-engine>=0.17.0",
    "grandalf>=0.8",
    "ipykernel>=7.0.1",
    "langchain-community>=0.3.30",
    "langchain-docling>=1.1.0",
    "langchain-openai>=0.3.34",
    "langfuse>=3.11.0",
    "langgraph>=0.6.8",
    "loguru>=0.7.3",
    "numexpr>=2.13.1",
    "pandas>=2.3.3",
    "ragas>=0.3.7",
    "rapidfuzz>=3.14.1",
    "sentence-transformers>=5.1.1",
]
